# ~/.tmuxinator/pname.yml
# you can make as many tabs as you wish...

project_name: pname
project_root: ~/Code/pname
# rvm: ruby-1.9.3-p125-perf@pname
# pre: sudo /etc/rc.d/mysqld start
tabs:
  - editor:
      layout: main-vertical
      panes:
        - vim
        - git pull
        - tork
  - shell: ls
  # - rails:
  #     layout: even-vertical
  #     panes:
  #         - rails db
  #         - rails c
  #         - rails s
  # - logs: tail -f log/development.log
  # - foreman: foreman
  # - sidekiq:
  #     layout: even-vertical
  #     panes:
  #         - redis-server
  #         - sleep 5; sidekiq
  # - capistrano:
  # - server: ssh me@myhost
